Check structure.sql is updated if there is migr
klaxit/ruby pull request #37
Opened 2020-09-22 16:09 UTC by Quiwin

**Before submitting your PR:**
- If you are contributing to `danger-klaxit`:
  - [ ] add newly created methods to `danger-klaxit/README.md`.
  - [ ] add tests!
- [ ] Explain in a few words the reason of your PR.
- [ ] Remove this section & submit 😉

--------------------------------------------------------------------------------

_description_

2020-09-23 10:14 UTC, BuonOmo requested changes
Quite nice, still a tiny bit of work imho. Tell me if something's unclear!

2020-09-23 10:14 UTC, BuonOmo commented on danger-klaxit/lib/danger_plugin.rb
> +    warn_for_not_updated_structure_sql
this looks quite important to me. What do you think?
```suggestion
    fail_for_not_updated_structure_sql
```

2020-09-23 10:14 UTC, BuonOmo commented on danger-klaxit/lib/danger_plugin.rb
> +    migration_files = (git.added_files - %w(Dangerfile)).grep(%r(db/migrate))
Don't see the point of removing Dangerfile here. bad Copy/pasta 🍝  I guess?
```suggestion
    migration_files = git.added_files.grep(%r(db/migrate))
```

2020-09-23 10:14 UTC, BuonOmo commented on danger-klaxit/lib/danger_plugin.rb
> +    if git.modified_files.grep(%r(db/structure.sql)).empty?
What about `schema.rb`?
```suggestion
    if git.modified_files.grep(%r(db/(?:structure\.sql|schema\.rb))).empty?
```

Idem for the message!

2020-09-23 10:14 UTC, BuonOmo commented on danger-klaxit/lib/danger_plugin.rb
> +    added_migrations_timestamps = migration_files.map do |elt|
what is elt?

2020-09-23 10:14 UTC, BuonOmo commented on danger-klaxit/lib/danger_plugin.rb
> +      warn("Some migrations timestamps are missing: #{missing_timestamps.join(", ")}")
I think this should also be a `fail`!

2020-09-23 17:40 UTC, BuonOmo approved these changes
LGTM!

2020-09-24 07:34 UTC, merged

2020-09-25 13:48 UTC, Quiwin commented
![](https://github.trello.services/images/mini-trello-icon.png) [(4.8) [DANGER] Faire marcher l'alerte de non-modification du structure.sql](https://trello.com/c/KVepTUD1/1127-48-danger-faire-marcher-lalerte-de-non-modification-du-structuresql)