Filter db/* files from check for missing spec
klaxit/ruby pull request #38
Opened 2020-10-06 14:22 UTC by Quiwin

Remove db/* files from check for missing spec, it was generating generating useless report.

2020-10-06 15:50 UTC, BuonOmo requested changes
I think the change you want to make is in `new_public_methods_by_ruby_file`, not after files have been parsed.

If you feel uncomfortable with the naming of any method, feel free to rename it!

2020-10-06 15:50 UTC, BuonOmo commented on danger-klaxit/lib/danger_plugin.rb
> +    db_files_regex = %r(db\/.*)
Do you wear both a belt and suspenders?

![image](https://user-images.githubusercontent.com/11378424/95225019-9f8dfb00-07fb-11eb-867b-d0e6d674d87b.png)

`%r(db/.*)` or `/db\//` would both do the trick here!

Moreover, I think you could just use `String#start_with?` which is more efficient, more correct (it is the beginning of the path) and straight to the point!

2020-10-07 07:44 UTC, JoakimKlaxit approved these changes

2020-10-07 07:59 UTC, BuonOmo approved these changes

2020-10-07 08:01 UTC, merged